import turtle

turtle.hideturtle()
turtle.pensize(3)
turtle.penup()
turtle.goto(10,200)
turtle.pendown()

turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Outlook", font = ("Times",14,"bold"))

turtle.color("blue")
turtle.goto(-35,160)
turtle.color("black")
turtle.write("Sunny", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(-80,120)
turtle.penup()
turtle.goto(-80,104)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Humidity", font = ("Times",14,"bold"))

turtle.color("blue")
turtle.goto(-110,62)
turtle.color("black")
turtle.write("High", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(-140,20)
turtle.penup()
turtle.goto(-140,6)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("N", font = ("Times",14,"bold"))
turtle.penup()
turtle.goto(-80,104)
turtle.pendown()

turtle.color("blue")
turtle.goto(-50,62)
turtle.color("black")
turtle.write("Normal", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(-20,20)
turtle.penup()
turtle.goto(-20,6)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Y", font = ("Times",14,"bold"))

turtle.penup()
turtle.goto(10,200)
turtle.pendown()
turtle.color("blue")
turtle.goto(10,160)
turtle.color("black")
turtle.write("Cloudy", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(10,120)
turtle.penup()
turtle.goto(10,104)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Y", font = ("Times",14,"bold"))

turtle.penup()
turtle.goto(10,200)
turtle.pendown()

turtle.color("blue")
turtle.goto(55,160)
turtle.color("black")
turtle.write("Rainy", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(100,120)
turtle.penup()
turtle.goto(100,104)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Wind", font = ("Times",14,"bold"))

turtle.color("blue")
turtle.goto(70,62)
turtle.color("black")
turtle.write("Weak", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(40,20)
turtle.penup()
turtle.goto(40,6)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("Y", font = ("Times",14,"bold"))
turtle.penup()
turtle.goto(100,104)
turtle.pendown()

turtle.color("blue")
turtle.goto(130,62)
turtle.color("black")
turtle.write("Strong", font = ("Times",12,"bold"))
turtle.color("blue")
turtle.goto(160,20)
turtle.penup()
turtle.goto(160,6)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(14)
turtle.end_fill()
turtle.color("black")
turtle.write("N", font = ("Times",14,"bold"))

turtle.penup()
turtle.goto(-80,-40)
turtle.pendown()
turtle.color("black")
turtle.write("The Decision Tree", font = ("Times",20,"bold"))

turtle.done()